// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using skestock.Infrastructure.Data;

#nullable disable

namespace skestock.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Romanian_100_CI_AI")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("skestock.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("CreatedDate", "Id")
                        .HasDatabaseName("IX_Categories_CreatedDate_Id");

                    b.HasIndex("LastModifiedDate", "Id")
                        .HasDatabaseName("IX_Categories_LastModifiedDate_Id");

                    b.HasIndex("Name", "Id")
                        .HasDatabaseName("IX_Categories_Name_Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("skestock.Domain.Entities.CategoryImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmationResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExtractedDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessingLeaseUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("CreatedDate", "Id")
                        .HasDatabaseName("IX_CategoryImportBatches_CreatedDate_Id");

                    b.HasIndex("UploadedAt", "Id")
                        .HasDatabaseName("IX_CategoryImportBatches_UploadedAt_Id");

                    b.HasIndex("UploadedByUserId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_CategoryImportBatches_UploadedByUserId_ClientRequestId")
                        .HasFilter("[ClientRequestId] IS NOT NULL");

                    b.ToTable("CategoryImportBatches");
                });

            modelBuilder.Entity("skestock.Domain.Entities.CategoryImportBatchFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryImportBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FileMetadataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FileMetadataId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("CategoryImportBatchId", "FileMetadataId")
                        .IsUnique()
                        .HasDatabaseName("IX_CategoryImportBatchFiles_BatchId_FileMetadataId");

                    b.ToTable("CategoryImportBatchFiles");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ClassBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ClosingQty")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OpeningQty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ItemId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("LocationId");

                    b.ToTable("ClassBalances");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ClassItemStockVisibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("HideWhenZeroStock")
                        .HasColumnType("bit");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ItemId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("LocationId");

                    b.HasIndex("ClassId", "ItemId", "LocationId")
                        .IsUnique();

                    b.ToTable("ClassItemStockVisibilities");
                });

            modelBuilder.Entity("skestock.Domain.Entities.DailyItemConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ClassId", "Date")
                        .HasDatabaseName("IX_DailyItemConsumptions_ClassId_Date");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ClassId", "Date"), new[] { "Quantity", "TotalValue" });

                    b.HasIndex("ItemId", "Date")
                        .HasDatabaseName("IX_DailyItemConsumptions_ItemId_Date");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ItemId", "Date"), new[] { "Quantity", "TotalValue" });

                    b.HasIndex("Date", "ItemId", "ClassId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyItemConsumptions_Date_ItemId_ClassId_LocationId");

                    b.ToTable("DailyItemConsumptions");
                });

            modelBuilder.Entity("skestock.Domain.Entities.FileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ETag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("FileMetadata");
                });

            modelBuilder.Entity("skestock.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SupplierReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("UserProfileId");

                    b.ToTable("GoodsReceipts");
                });

            modelBuilder.Entity("skestock.Domain.Entities.GoodsReceiptImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExtractedDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FileMetadataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ResultingGoodsReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FileMetadataId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("ResultingGoodsReceiptId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("GoodsReceiptImports");
                });

            modelBuilder.Entity("skestock.Domain.Entities.GoodsReceiptImportLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MatchedItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RawItemText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ImportId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("LocationId");

                    b.HasIndex("MatchedItemId");

                    b.ToTable("GoodsReceiptImportLines");
                });

            modelBuilder.Entity("skestock.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPerishable")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MinThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Latin1_General_100_CI_AI");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AI");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasFilter("[Sku] IS NOT NULL");

                    b.HasIndex("CreatedDate", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_Items_CreatedDate_Id");

                    b.HasIndex("LastModifiedDate", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_Items_LastModifiedDate_Id");

                    b.HasIndex("Name", "Id")
                        .HasDatabaseName("IX_Items_Name_Id");

                    b.HasIndex("CategoryId", "CreatedDate", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Items_CategoryId_CreatedDate_Id");

                    b.HasIndex("IsActive", "CreatedDate", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Items_IsActive_CreatedDate_Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ItemImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmationResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExtractedDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessingLeaseUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("CreatedDate", "Id")
                        .HasDatabaseName("IX_ItemImportBatches_CreatedDate_Id");

                    b.HasIndex("LastModifiedDate", "Id")
                        .HasDatabaseName("IX_ItemImportBatches_LastModifiedDate_Id");

                    b.HasIndex("UploadedAt", "Id")
                        .HasDatabaseName("IX_ItemImportBatches_UploadedAt_Id");

                    b.HasIndex("UploadedByUserId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItemImportBatches_UploadedByUserId_ClientRequestId")
                        .HasFilter("[ClientRequestId] IS NOT NULL");

                    b.HasIndex("Status", "CreatedDate", "Id")
                        .HasDatabaseName("IX_ItemImportBatches_Status_CreatedDate_Id");

                    b.ToTable("ItemImportBatches");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ItemImportBatchFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FileMetadataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemImportBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FileMetadataId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("ItemImportBatchId", "FileMetadataId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItemImportBatchFiles_BatchId_FileMetadataId");

                    b.ToTable("ItemImportBatchFiles");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ItemPurchaseStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AverageUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastPurchasedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PurchaseCount")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ItemId", "Scope")
                        .HasDatabaseName("IX_ItemPurchaseStatistics_ItemId_Scope");

                    b.HasIndex("Scope", "ClassId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItemPurchaseStatistics_Scope_ClassId_ItemId");

                    b.ToTable("ItemPurchaseStatistics");
                });

            modelBuilder.Entity("skestock.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("skestock.Domain.Entities.OrderList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("OrderLists");
                });

            modelBuilder.Entity("skestock.Domain.Entities.OrderListLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("OrderListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ItemId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("OrderListId");

                    b.ToTable("OrderListLines");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ScheduledJobRun", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("JobName");

                    b.ToTable("ScheduledJobRuns");
                });

            modelBuilder.Entity("skestock.Domain.Entities.SchoolClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("SchoolClasses");
                });

            modelBuilder.Entity("skestock.Domain.Entities.StockBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("GoodsReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceivedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReceivedClassId", "LocationId", "ItemId")
                        .HasDatabaseName("IX_StockBatches_ReceivedClassId_LocationId_ItemId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ReceivedClassId", "LocationId", "ItemId"), new[] { "Quantity", "ExpiryDate" });

                    b.ToTable("StockBatches");
                });

            modelBuilder.Entity("skestock.Domain.Entities.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GoodsReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.HasIndex("ClassId", "ItemId", "LocationId", "CreatedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("IX_StockTransactions_ClassId_ItemId_LocationId_CreatedAt");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("skestock.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONCAT([FirstName], ' ',  [LastName])", true);

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("LastModifiedById");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("skestock.Domain.Queues.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClaimedUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("QueueName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "ClaimedUntilUtc", "CreatedAtUtc")
                        .HasFilter("[ProcessedAtUtc] IS NULL");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("skestock.Domain.Queues.ProcessedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ProcessedMessages");
                });

            modelBuilder.Entity("skestock.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("skestock.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("skestock.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skestock.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("skestock.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("skestock.Domain.Entities.Category", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("skestock.Domain.Entities.CategoryIcon", "Icon", b1 =>
                        {
                            b1.Property<Guid>("CategoryId");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1
                                .ToJson("Icon")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("Icon");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.CategoryImportBatch", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("skestock.Domain.Entities.ImportBatchHistory", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Attempt")
                                .HasColumnType("int");

                            b1.Property<Guid>("CategoryImportBatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Message")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("CategoryImportBatchId");

                            b1.HasIndex("CreatedAtUtc");

                            b1.ToTable("CategoryImportBatchHistory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CategoryImportBatchId");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("History");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("skestock.Domain.Entities.CategoryImportBatchFile", b =>
                {
                    b.HasOne("skestock.Domain.Entities.CategoryImportBatch", "Batch")
                        .WithMany("Files")
                        .HasForeignKey("CategoryImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("CreatedBy");

                    b.Navigation("FileMetadata");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ClassBalance", b =>
                {
                    b.HasOne("skestock.Domain.Entities.SchoolClass", "Class")
                        .WithMany("Balances")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Item", "Item")
                        .WithMany("ClassBalances")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Location", "Location")
                        .WithMany("ClassBalances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("Item");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ClassItemStockVisibility", b =>
                {
                    b.HasOne("skestock.Domain.Entities.SchoolClass", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.DailyItemConsumption", b =>
                {
                    b.HasOne("skestock.Domain.Entities.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("skestock.Domain.Entities.FileMetadata", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("skestock.Domain.Entities.SchoolClass", "Class")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", null)
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.GoodsReceiptImport", b =>
                {
                    b.HasOne("skestock.Domain.Entities.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.GoodsReceipt", "ResultingGoodsReceipt")
                        .WithMany()
                        .HasForeignKey("ResultingGoodsReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("FileMetadata");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("ResultingGoodsReceipt");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("skestock.Domain.Entities.GoodsReceiptImportLine", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.GoodsReceiptImport", "Import")
                        .WithMany("Lines")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Item", "MatchedItem")
                        .WithMany()
                        .HasForeignKey("MatchedItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Import");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Location");

                    b.Navigation("MatchedItem");
                });

            modelBuilder.Entity("skestock.Domain.Entities.Item", b =>
                {
                    b.HasOne("skestock.Domain.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ItemImportBatch", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("skestock.Domain.Entities.ImportBatchHistory", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Attempt")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("ItemImportBatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Message")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("CreatedAtUtc");

                            b1.HasIndex("ItemImportBatchId");

                            b1.ToTable("ItemImportBatchHistory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ItemImportBatchId");
                        });

                    b.Navigation("CreatedBy");

                    b.Navigation("History");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ItemImportBatchFile", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.ItemImportBatch", "Batch")
                        .WithMany("Files")
                        .HasForeignKey("ItemImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("CreatedBy");

                    b.Navigation("FileMetadata");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ItemPurchaseStatistic", b =>
                {
                    b.HasOne("skestock.Domain.Entities.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("skestock.Domain.Entities.Location", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Location", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("skestock.Domain.Entities.OrderList", b =>
                {
                    b.HasOne("skestock.Domain.Entities.SchoolClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.OrderListLine", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.OrderList", "OrderList")
                        .WithMany("Lines")
                        .HasForeignKey("OrderListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Item");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("OrderList");
                });

            modelBuilder.Entity("skestock.Domain.Entities.SchoolClass", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.StockBatch", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Batches")
                        .HasForeignKey("GoodsReceiptId");

                    b.HasOne("skestock.Domain.Entities.Item", "Item")
                        .WithMany("Batches")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Location", "Location")
                        .WithMany("Batches")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.SchoolClass", "ReceivedClass")
                        .WithMany("BatchesReceived")
                        .HasForeignKey("ReceivedClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Item");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Location");

                    b.Navigation("ReceivedClass");
                });

            modelBuilder.Entity("skestock.Domain.Entities.StockTransaction", b =>
                {
                    b.HasOne("skestock.Domain.Entities.StockBatch", "Batch")
                        .WithMany("Transactions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.SchoolClass", "Class")
                        .WithMany("Transactions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Transactions")
                        .HasForeignKey("GoodsReceiptId");

                    b.HasOne("skestock.Domain.Entities.Item", "Item")
                        .WithMany("Transactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Domain.Entities.Location", "Location")
                        .WithMany("Transactions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Item");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("skestock.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("skestock.Domain.Entities.UserProfile", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("skestock.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("UserProfile")
                        .HasForeignKey("skestock.Domain.Entities.UserProfile", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skestock.Domain.Entities.UserProfile", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .HasPrincipalKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("skestock.Domain.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("skestock.Domain.Entities.CategoryImportBatch", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("skestock.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("skestock.Domain.Entities.GoodsReceiptImport", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("skestock.Domain.Entities.Item", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("ClassBalances");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("skestock.Domain.Entities.ItemImportBatch", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("skestock.Domain.Entities.Location", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("ChildLocations");

                    b.Navigation("ClassBalances");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("skestock.Domain.Entities.OrderList", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("skestock.Domain.Entities.SchoolClass", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("BatchesReceived");

                    b.Navigation("GoodsReceipts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("skestock.Domain.Entities.StockBatch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("skestock.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("skestock.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
