export const realtimeEventNames = {
  categoryCreated: 'CategoryCreated',
  categoryUpdated: 'CategoryUpdated',
  categoryImportBatchCreated: 'CategoryImportBatchCreated',
  categoryImportBatchProcessed: 'CategoryImportBatchProcessed',
  categoryImportBatchConfirmed: 'CategoryImportBatchConfirmed',
  itemCreated: 'ItemCreated',
  itemUpdated: 'ItemUpdated',
  itemDisabled: 'ItemDisabled',
  itemEnabled: 'ItemEnabled',
  itemImportBatchCreated: 'ItemImportBatchCreated',
  itemImportBatchProcessed: 'ItemImportBatchProcessed',
  itemImportBatchConfirmed: 'ItemImportBatchConfirmed',
  goodsReceiptImportCreated: 'GoodsReceiptImportCreated',
  goodsReceiptImportProcessed: 'GoodsReceiptImportProcessed',
  goodsReceiptImportConfirmed: 'GoodsReceiptImportConfirmed',
  supplyListCreated: 'SupplyListCreated',
  supplyListUpdated: 'SupplyListUpdated',
  supplyListDisabled: 'SupplyListDisabled',
  supplyListEnabled: 'SupplyListEnabled',
  orderListCreated: 'OrderListCreated',
  orderListSubmitted: 'OrderListSubmitted',
  orderListCancelled: 'OrderListCancelled',
  orderListReopened: 'OrderListReopened',
  stockAdjusted: 'StockAdjusted',
  stockMoved: 'StockMoved',
  stockBatchCreated: 'StockBatchCreated',
  classItemStockVisibilityChanged: 'ClassItemStockVisibilityChanged'
} as const;

export type RealtimeEventName = typeof realtimeEventNames[keyof typeof realtimeEventNames];
